### ISSUE TITLE
How can i use library with project react-native with typescript?

### ISSUE THREAD

**Issue by vannt1991** [prscX/react-native-app-tour#106]
i try to implement showcase using this library, but after import library to use in my project react-native using typescript it showing error :
<img width="1281" alt="Screen Shot 2020-08-25 at 18 28 40" src="https://user-images.githubusercontent.com/8731361/91169518-b2dc7f80-e701-11ea-9816-182ea42793ac.png">

```
Could not find a declaration file for module 'react-native-app-tour'. '/Users/xxx/Desktop/xxx/x-xx/node_modules/react-native-app-tour/RNAppTour.js' implicitly has an 'any' type.
  Try `npm install @types/react-native-app-tour` if it exists or add a new declaration (.d.ts) file containing `declare module 'react-native-app-tour';`ts(7016)

```
Do u have any suggestion for this issue? thanks and regards.

**Comment by vaibhavhrt** [comment]
add `declare module 'react-native-app-tour';` somewhere to make it disappear

**Comment by isosphere** [comment]
Adding the above as suggested results in the following for me:

> Invalid module name in augmentation. Module 'react-native-app-tour' resolves to an untyped module at '_(path omitted)_/node_modules/react-native-app-tour/RNAppTour.js', which cannot be augmented.ts(2665)

**Comment by tinezmatias** [comment]
try this:
1. create a file in somewhere: index.d.ts
2. add this line: declare module 'react-native-app-tour';

> Adding the above as suggested results in the following for me:
> 
> > Invalid module name in augmentation. Module 'react-native-app-tour' resolves to an untyped module at '_(path omitted)_/node_modules/react-native-app-tour/RNAppTour.js', which cannot be augmented.ts(2665)

**Comment by vannt1991** [comment]
Thanks so much for all your help. I closed this issue.
