### ISSUE TITLE
Tap anywhere to continue? Including outer circle?

### ISSUE THREAD

**Issue by Noitidart** [prscX/react-native-app-tour#13]
I set "cancelable" to true. However tapping on the outer circle is not continuing. The tap has to be either within target circle, or outside outer circle. Is it possible to make it tap anywhere to continue? Because when I point out buttons, from a users perspective, he might think tapping within the target circle, will trigger the buttons effect.

**Comment by prscX** [comment]
Thanks @Noitidart for raising the query.

I have checked `cancelable` on both platforms and it is working as expected. Can you please verify the same.

Thanks
</ Pranav >

**Comment by Noitidart** [comment]
Thanks much for that test. I only tested on Android device. When I tried pressing on the "elevated" circle it wouldn't cancel. I would have to press in the inner circle. Or outside the "elevated" outer circle. I'll test again with a screenshot.

I'll also test on iOS and share the results from there.

**Comment by prscX** [comment]
Got your point @Noitidart. I have check [Android: KeepSafe/TapTargetView](https://github.com/KeepSafe/TapTargetView#simple-usage) library props. According to their documentation, cancellable is only for below area:

`Whether tapping outside the outer circle dismisses the view`

Looks like it does not support cancellable on the outer circle. However I have verified the same for iOS and it works.

Thanks
</ Pranav >

**Comment by Noitidart** [comment]
Ahh. Thank you very much brother for that. Should we close this topic out then?

**Comment by prscX** [comment]
I think you can close this, since nothing can be done to this library in order to fix it.

However please feel free to share/raise your concern to the native library [KeepSafe/TapTargetView](https://github.com/KeepSafe/TapTargetView).

Thanks
</ Pranav >

**Comment by Noitidart** [comment]
Thanks!

**Comment by Noitidart** [comment]
Just a note when we get some time - a contributor from there says its possible like this - https://github.com/KeepSafe/TapTargetView/issues/293#issuecomment-394068930

**Comment by prscX** [comment]
Thanks for @Noitidart raising the query to [KeepSafe/TapTargetView](https://github.com/KeepSafe/TapTargetView). 

Based on suggestion I have enabled cancellable property on outer circle. Can you please install latest version `0.0.9` and verify the same.

Please let me know incase you face any issues.

Thanks
</ Pranav >

**Comment by Noitidart** [comment]
For sure I'll install this on my android build and share how it goes. I'll do this later today please. :)

**Comment by Noitidart** [comment]
Just upgraded to 0.0.9 and install works flawlessly and also pressing on outter circle also cancels! Thank you @prscX ! :)
