### ISSUE TITLE
Cannot do pod install or pod repo update

### ISSUE THREAD

**Issue by Noitidart** [prscX/react-native-app-tour#15]
This is working great for me on Android now.

However on iOS I am having problems.

I have linked it already.

I then try to go to cd ../node_modules/react-native-app-tour/ios then I try pod install and that fails with:
```
Noitidarts-Mac-mini:ios noitidart$ pod install
Analyzing dependencies
[!] Unable to satisfy the following requirements:

- `MaterialShowcase (= 0.5.1)` required by `Podfile`

None of your spec sources contain a spec satisfying the dependency: `MaterialShowcase (= 0.5.1)`.

You have either:
 * out-of-date source repos which you can update with `pod repo update` or with `pod install --repo-update`.
 * mistyped the name or version.
 * not added the source repo that hosts the Podspec to your Podfile.

Note: as of CocoaPods 1.0, `pod repo update` does not happen on `pod install` by default.

[!] Automatically assigning platform ios with version 8.0 on target RNAppTour because no platform was specified. Please specify a platform for this target in your Podfile. See `https://guides.cocoapods.org/syntax/podfile.html#platform`.
```

So then, per the readme, I try pod repo update first:

But then that fails with:

```
Noitidarts-Mac-mini:ios noitidart$ pod install --repo-update
Updating local specs repositories
[!] Failed to connect to GitHub to update the CocoaPods/Specs specs repo - Please check if you are offline, or that GitHub is down
```

This is real weird because I am online, and github is up.

Any ideas please?

**Comment by Noitidart** [comment]
I also don't have material-showcase-ios dir in my node_moduels folder as is seen in the gif.

**Comment by Noitidart** [comment]
In XCode the error given is:

```
Apple Mach-O Linker (ld) Error Group
: Linker command failed with exit code 1 (use -v to see invocation)
```

**Comment by Noitidart** [comment]
Oh I got `pod install` to work. I had to first do `pod remove master`, then `pod setup`:

```
Noitidarts-Mac-mini:ios noitidart$ pod repo remove master
Removing spec repo `master`
Noitidarts-Mac-mini:ios noitidart$ pod setup
Setting up CocoaPods master repo
  $ /usr/bin/git clone https://github.com/CocoaPods/Specs.git master --progress
  Cloning into 'master'...
  remote: Counting objects: 2185928, done.
  remote: Compressing objects: 100% (259/259), done.
  remote: Total 2185928 (delta 112), reused 35 (delta 35), pack-reused 2185623
  Receiving objects: 100% (2185928/2185928), 542.08 MiB | 7.88 MiB/s, done.
  Resolving deltas: 100% (1246599/1246599), done.
  Checking out files: 100% (241908/241908), done.
Setup completed
Noitidarts-Mac-mini:ios noitidart$ pod install
Analyzing dependencies
Downloading dependencies
Installing MaterialShowcase (0.5.1)
Generating Pods project
Integrating client project
Sending stats
Pod installation complete! There is 1 dependency from the Podfile and 1 total pod installed.

[!] Automatically assigning platform `ios` with version `8.0` on target `RNAppTour` because no platform was specified. Please specify a platform for this target in your Podfile. See `https://guides.cocoapods.org/syntax/podfile.html#platform`.

[!] The Podfile contains framework or static library targets (RNAppTour), for which the Podfile does not contain host targets (targets which embed the framework).
If this project is for doing framework development, you can ignore this message. Otherwise, add a target to the Podfile that embeds these frameworks to make this message go away (e.g. a test target).

[!] The `RNAppTour [Debug]` target overrides the `OTHER_LDFLAGS` build setting defined in `Pods/Target Support Files/Pods-RNAppTour/Pods-RNAppTour.debug.xcconfig'. This can lead to problems with the CocoaPods installation
    - Use the `$(inherited)` flag, or
    - Remove the build settings from the target.

[!] The `RNAppTour [Release]` target overrides the `OTHER_LDFLAGS` build setting defined in `Pods/Target Support Files/Pods-RNAppTour/Pods-RNAppTour.release.xcconfig'. This can lead to problems with the CocoaPods installation
    - Use the `$(inherited)` flag, or
    - Remove the build settings from the target.
Noitidarts-Mac-mini:ios noitidart$ pod repo update
Updating spec repo `master`
[!] Failed to connect to GitHub to update the CocoaPods/Specs specs repo - Please check if you are offline, or that GitHub is down
```

While `pod install` worked. `pod repo update` did not work.

**Comment by Noitidart** [comment]
I still don't see `MaterialShowcase.xcodeproj` in the node_modules though. I see some new files in the pod folder though - https://i.imgur.com/F0adc9i.png

I did find it when I clicked `+` in "Embed Binaries". Screenshot here - https://i.imgur.com/K5Q6HGu.png

However pressing XCode to build is still failing. :(

Any ideas please?

**Comment by Noitidart** [comment]
I got past the linking error and am now getting this error in MaterialShowcase - screenshot: https://i.imgur.com/xDZJXQ0.png

```
MaterialShowcase Group
Dependency Analysis Error Group
The “Swift Language Version” (SWIFT_VERSION) build setting must be set to a supported value for targets which use Swift. This setting can be set in the build settings editor.
```

**Comment by Noitidart** [comment]
I set swift language version to 3.2 as in this screenshot - https://i.imgur.com/YIxv2bf.png

This fixed that swift version error but now I'm back to getting linking error:

```
Apple Mach-O Linker (ld) Error Group
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```
Right clicking and pressing "reveal in log" shows this - https://i.imgur.com/q7CPW4p.png

```
Ld /Users/noitidart/Library/Developer/Xcode/DerivedData/did-fifcuvpibfbrebfkuolgzjzmtoox/Build/Products/Debug-iphoneos/did.app/did normal arm64
    cd /Users/noitidart/Documents/Did/ios
    export IPHONEOS_DEPLOYMENT_TARGET=8.0
    export PATH="/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/usr/bin:/Applications/Xcode.app/Contents/Developer/usr/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin"
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -arch arm64 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS11.2.sdk -L/Users/noitidart/Library/Developer/Xcode/DerivedData/did-fifcuvpibfbrebfkuolgzjzmtoox/Build/Products/Debug-iphoneos -F/Users/noitidart/Library/Developer/Xcode/DerivedData/did-fifcuvpibfbrebfkuolgzjzmtoox/Build/Products/Debug-iphoneos -filelist /Users/noitidart/Library/Developer/Xcode/DerivedData/did-fifcuvpibfbrebfkuolgzjzmtoox/Build/Intermediates.noindex/did.build/Debug-iphoneos/did.build/Objects-normal/arm64/did.LinkFileList -Xlinker -rpath -Xlinker @executable_path/Frameworks -miphoneos-version-min=8.0 -Xlinker -object_path_lto -Xlinker /Users/noitidart/Library/Developer/Xcode/DerivedData/did-fifcuvpibfbrebfkuolgzjzmtoox/Build/Intermediates.noindex/did.build/Debug-iphoneos/did.build/Objects-normal/arm64/did_lto.o -Xlinker -no_deduplicate -fembed-bitcode-marker -fobjc-arc -fobjc-link-runtime -ObjC -lc++ -framework MaterialShowcase /Users/noitidart/Library/Developer/Xcode/DerivedData/did-fifcuvpibfbrebfkuolgzjzmtoox/Build/Products/Debug-iphoneos/libRCTBlob.a /Users/noitidart/Library/Developer/Xcode/DerivedData/did-fifcuvpibfbrebfkuolgzjzmtoox/Build/Products/Debug-iphoneos/libRCTAnimation.a /Users/noitidart/Library/Developer/Xcode/DerivedData/did-fifcuvpibfbrebfkuolgzjzmtoox/Build/Products/Debug-iphoneos/libReact.a /Users/noitidart/Library/Developer/Xcode/DerivedData/did-fifcuvpibfbrebfkuolgzjzmtoox/Build/Products/Debug-iphoneos/libRCTAnimation.a /Users/noitidart/Library/Developer/Xcode/DerivedData/did-fifcuvpibfbrebfkuolgzjzmtoox/Build/Products/Debug-iphoneos/libRCTActionSheet.a /Users/noitidart/Library/Developer/Xcode/DerivedData/did-fifcuvpibfbrebfkuolgzjzmtoox/Build/Products/Debug-iphoneos/libRCTGeolocation.a /Users/noitidart/Library/Developer/Xcode/DerivedData/did-fifcuvpibfbrebfkuolgzjzmtoox/Build/Products/Debug-iphoneos/libRCTImage.a /Users/noitidart/Library/Developer/Xcode/DerivedData/did-fifcuvpibfbrebfkuolgzjzmtoox/Build/Products/Debug-iphoneos/libRCTLinking.a /Users/noitidart/Library/Developer/Xcode/DerivedData/did-fifcuvpibfbrebfkuolgzjzmtoox/Build/Products/Debug-iphoneos/libRCTNetwork.a /Users/noitidart/Library/Developer/Xcode/DerivedData/did-fifcuvpibfbrebfkuolgzjzmtoox/Build/Products/Debug-iphoneos/libRCTSettings.a /Users/noitidart/Library/Developer/Xcode/DerivedData/did-fifcuvpibfbrebfkuolgzjzmtoox/Build/Products/Debug-iphoneos/libRCTText.a /Users/noitidart/Library/Developer/Xcode/DerivedData/did-fifcuvpibfbrebfkuolgzjzmtoox/Build/Products/Debug-iphoneos/libRCTVibration.a /Users/noitidart/Library/Developer/Xcode/DerivedData/did-fifcuvpibfbrebfkuolgzjzmtoox/Build/Products/Debug-iphoneos/libRCTWebSocket.a -lRNSnackbar -lRNAppTour -Xlinker -dependency_info -Xlinker /Users/noitidart/Library/Developer/Xcode/DerivedData/did-fifcuvpibfbrebfkuolgzjzmtoox/Build/Intermediates.noindex/did.build/Debug-iphoneos/did.build/Objects-normal/arm64/did_dependency_info.dat -o /Users/noitidart/Library/Developer/Xcode/DerivedData/did-fifcuvpibfbrebfkuolgzjzmtoox/Build/Products/Debug-iphoneos/did.app/did

ld: framework not found MaterialShowcase
clang: error: linker command failed with exit code 1 (use -v to see invocation)

```

I'm going through this here because I need help, but also because it might help out others too. :)

**Comment by prscX** [comment]
Thanks @Noitidart for sharing the issues you are facing.

Looks like the native swift library is not properly added to your project. It is showing in red color.

Can you please add native library into your project `Embedded Binaries & Linked Frameworks`. You can follow setup gif for the same.

Let me know in case it does not work.

Thanks
</ Pranav >

**Comment by Noitidart** [comment]
Thanks very much @prscX for your continued help.

After doing `pod install` I saw this - https://i.imgur.com/F0adc9i.png - in the gif it shows you have a `MaterialShowCase.xcodeproj`. 

I didn't see a `MaterialShowCase.xcodeproj`. But when I went to add it to embed binaries & linked frameworks this showed - https://i.imgur.com/K5Q6HGu.png - which I added. So i'm very confused :(

**Comment by Noitidart** [comment]
I tried again in a brand new `react-native init` project. Same result :( (except no problems with pod anymore). Shold I take a screencast and upload?

**Comment by prscX** [comment]
Hi @Noitidart, We can connect through TeamViewer and fix the issue. Today my health is not good, can we connect tomorrow or day after tomorrow?. Pleade let me know your convenient timings.

Thanks
< /Pranav >

**Comment by Noitidart** [comment]
Thank you sir you are toooo kind!! Get well soon brother! :)

I am available any time you are. I am the student you are the teacher. I will work on your any time you are available. :)

My timezone is Pacific Standard Time. Any time though that is good for you is good for me. :) Thank you!

**Comment by prscX** [comment]
@Noitidart: Can we sync today night - IST which is your morning?

Thanks
</ Pranav >

**Comment by Noitidart** [comment]
Thanks @prscX that would be great! Its 245a here right now haha. If you're available now though I can do it too. :)

**Comment by Noitidart** [comment]
I emailed you, hope you are feeling better! :)

**Comment by Noitidart** [comment]
Yesss! It works now thank you @prscX !!! I will create a video and update readme with instructions for this fallback method, is it ok if we leave this issue open till I create this PR?

Thanks again soooo much!

**Comment by Noitidart** [comment]
I have created a youtube video of this. I am going to try to do a production build to make sure I did everything correct - right now a bit stuck - issue #19 - Im updating my macos right now - then when that builds then i have verified this process is correct, then will PR this please - https://youtu.be/iBjsCrEtYW4 :)

**Comment by congnguyen91** [comment]
Thanks for @Noitidart, @prscX ! You are enthusiastic persons! Hope this lib is going to be improved & better :D 
I will come back this lib to support some issues after I finish my rush project.

Thanks,
Cong

**Comment by prscX** [comment]
Thanks a lot @Noitidart for sharing the video w.r.t iOS installation. It will be very useful for folks facing the iOS installation issues. I will update the `README` with the video reference.

Definitely @congnguyen91, Looking forward to collaborate/work with you on awesome stuffs 😄.   

Thanks
</ Pranav >

**Comment by Noitidart** [comment]
Awesome team work. I am so glad to work with you both! Thank you!

I just verified that this video is correct. We should probably mention that they need to update XCode to latest. As when I did that, then the production build worked fine.

**Comment by Noitidart** [comment]
Oh @prscX thanks so much for updating readme. I was making PR now, but saw it was already in there. Sorry about the delay, I was trying to verify if it worked for production build too. :) Thanks also very very much for mentioning @Noitidart for the video! You are too kind you didn't have to :)

**Comment by nicolascanto** [comment]
> I have created a youtube video of this. I am going to try to do a production build to make sure I did everything correct - right now a bit stuck - issue #19 - Im updating my macos right now - then when that builds then i have verified this process is correct, then will PR this please - https://youtu.be/iBjsCrEtYW4 :)

thanks for the video :)

**Comment by Noitidart** [comment]
Thank you @nicolascanto !

**Comment by ravifullestop** [comment]
Still the issue : mv: rename /Users/team/Library/Developer/Xcode/DerivedData/abcd-evkuoknqqxlrrueyipqdrrbkpxqt/Build/Products/Debug-iphonesimulator/abcd.app/Frameworks/MaterialShowcase.framework/MaterialShowcase-merged to /Users/team/Library/Developer/Xcode/DerivedData/abcd-evkuoknqqxlrrueyipqdrrbkpxqt/Build/Products/Debug-iphonesimulator/abcd.app/Frameworks/MaterialShowcase.framework/MaterialShowcase: No such file or directory
Command PhaseScriptExecution failed with a nonzero exit code
