### ISSUE TITLE
Hide status bar in Android app

### ISSUE THREAD

**Issue by tamirrab** [prscX/react-native-app-tour#17]
Hi
I hide status bar in my app but when the tour appear - the status bar show and there is a glitch when it's shows up

how can I cancel the status bar?

thanks allot

**Comment by Noitidart** [comment]
What code are you using to hide status bar?

**Comment by tamirrab** [comment]
import {StatusBar} from 'react-native'

 StatusBar.setHidden(true, true);

**Comment by prscX** [comment]
Thanks @tamirrab for raising the issue.

One way of doing this in your app project settings you can set the config to hide the status bar permanently. 

- **iOS:** Deployment Info configuration you can enable the hide status bar option:

<img width="651" alt="screen shot 2018-06-05 at 2 30 17 pm" src="https://user-images.githubusercontent.com/28862892/40966126-3e403162-68cd-11e8-987a-53b54583538d.png">

- **Android:** Similarly we can enable the same on Android as well.

Please let us know in case you have any concerns with the solution.

Thanks
</ Pranav >

**Comment by tamirrab** [comment]
The problem is only on Android.
On iOS is working good as expected.

even if I disable permanently on Android it's still showing the status bar when I play the tour

**Comment by congnguyen91** [comment]
@prscX, @tamirrab  It seems like a bug in TapTargetView lib - Should rate for android native lib. Request an option for hiding StatusBar

**Comment by prscX** [comment]
Hi @tamirrab, @congnguyen91, I guess @xiphirx is tracking this feature as part of `V2.0 Features` list. Please find below reference of the same:

- [ISSUE: 227 - 2.0 Features](https://github.com/KeepSafe/TapTargetView/issues/227)
- [ISSUE: 222 - Status bar shows up](https://github.com/KeepSafe/TapTargetView/issues/222)

Thanks
</ Pranav >
