### ISSUE TITLE
framework not found MaterialShowcase for architecture armv7

### ISSUE THREAD

**Issue by Noitidart** [prscX/react-native-app-tour#19]
Hey there again. When we had this problem for debug mode we fixed it by copying the file over.

However that problem is for arm64. When doing "archive" to build release of app, I also get this error, but doing the copy "MaterialShowcase.framework" from child directory to parent directory works here also.

However I then get the same error but for armv7. Do you know how to fix this armv7 error? Maybe as easy as copying MaterialShowcase file somewhere?

I tried this Stackoverflow topic but no luck - https://stackoverflow.com/questions/37321107/ld-framework-not-found-adsupport-for-architecture-armv7

**Comment by Noitidart** [comment]
Someone recommended to update my XCode I'm trying that now.

**Comment by tamirrab** [comment]
You need to Pod install from the node_modules:

cd node_modules/react-native-app-tour/ios && pod install

then from the folder node_modules/react-native-app-tour/ios drag the pods file to xCode under "Frameworks".

After that Add "MaterialShowcase.framework" from the pods file that you added

**Comment by Noitidart** [comment]
Ohhh I was putting into the "Libraries" folder. Thank you will try this out!

**Comment by Noitidart** [comment]
I actually kept using the Libraries folder. My mac os and xcode update just finished. I'm on High Sierra now and don't get this problem. Very interesting.
