### ISSUE TITLE
android Nothing is shown

### ISSUE THREAD

**Issue by j-mendez** [prscX/react-native-app-tour#21]
Currently on android I cannot get the intro to appear like iOS smoothly. I need to put the app in the background and return to display it. Also the other steps do not come even with collapsible = true on the view.

**Comment by prscX** [comment]
Thanks @jeffreymendez1993 raising the issue.

Can you please share your code snippet where you are invoking the AppTour.ShowSequence.

Thanks
</ Pranav >

**Comment by j-mendez** [comment]
<img width="598" alt="screen shot 2018-06-10 at 11 55 48 pm" src="https://user-images.githubusercontent.com/8095978/41212149-de46b3d0-6d09-11e8-8c7b-686cef96a53b.png">

**Comment by j-mendez** [comment]
works fine when I use the tour with only my bottom tab bar. When I add a item that is from my absolute position top It doesn't render. 
<img width="770" alt="screen shot 2018-06-10 at 11 57 43 pm" src="https://user-images.githubusercontent.com/8095978/41212185-17d01b32-6d0a-11e8-88f0-dfc794987ed3.png"> passing the function as a prop and adding the next items from my sub component.

**Comment by j-mendez** [comment]
works fine on iOS and works fine when Im not trying to use the sub component
<img width="724" alt="screen shot 2018-06-11 at 12 00 00 am" src="https://user-images.githubusercontent.com/8095978/41212231-6a555c96-6d0a-11e8-9aa2-d1862bb03300.png">

**Comment by prscX** [comment]
@jeffreymendez1993: Ideally you should not put settimeout for capturing ref but please add settimeout for invoking app tour. 

Please refer example project for the same

Thanks
</ Pranav >

**Comment by j-mendez** [comment]
@prscX will remove the timeout and try again. Was trying to set the order with different timeouts.

**Comment by j-mendez** [comment]
@prscX Does not solve the issue. The modal is shown but the item is behind it. I think the issue could be from it being a absolute position item. 
![screenshot_1528734079](https://user-images.githubusercontent.com/8095978/41244347-c38b5bcc-6d72-11e8-85d5-48757e6dc98d.png)

**Comment by congnguyen91** [comment]
Hey you, @jeffreymendez1993 

I think you should put your refs with View, Touch, ... that is the base component of React Native - It's easily to get Refs ->  So try it by replacing
```
<Icon ref={....} />  by 

<View  ref={  
  if(ref) {
     // must check null to avoid crash
    // App tour add ref here
  }
} > <Icon  /* remove ref*/ />
```
Contact me if you don't want to share code here => I will help you with some suggestions 
My facebook: https://www.facebook.com/ntcong91

**Comment by congnguyen91** [comment]
One case => If your component is a customized component
You can pass like this: 
```
<CustomizedComponent onRef={(newRef) => {
     if (newRef)  // must have this - be careful with the second callback with null 
} } />
// ======
class CustomizedComponent extends Component  {
  ....
  
 render() {
     return   (<View ref={(viewRef) => {
        // Should put ref with base/native component like- not with customized component like <Icon
        const { onRef } = this.props;
        viewRef && onRef && onRef(viewRef)
      }}>
          ....
    </View>)
 }
}

**Comment by j-mendez** [comment]
@congnguyen91 That does not change anything. The ref was being passed normally through the icon component anyways. Tried your solution and no luck.

**Comment by congnguyen91** [comment]
@jeffreymendez1993  How about replacing with Animated.View by View ?

**Comment by congnguyen91** [comment]
Ah, @jeffreymendez1993  Please convert your stateless component to Normal Component 
```
export searchInput = () => {
...
}

To

class SearchInput extends Component {
  constructor(props) {
     super(props);
  }

  render() {
  }
}
```

**Comment by prscX** [comment]
@jeffreymendez1993: Can you please try below solution.

If you are taking `ref` of View which just contains children, please add `collapsable:false` prop to the View. [view#collapsable](https://facebook.github.io/react-native/docs/view#collapsable)

Please verify this by upgrading the library to it's latest version. 

Please let us know if it does not work.

Thanks
</ Pranav >

**Comment by ithustle** [comment]
> @jeffreymendez1993: Can you please try below solution.
> 
> If you are taking `ref` of View which just contains children, please add `collapsable:false` prop to the View. [view#collapsable](https://facebook.github.io/react-native/docs/view#collapsable)
> 
> Please verify this by upgrading the library to it's latest version.
> 
> Please let us know if it does not work.
> 
> Thanks
> </ Pranav >

It works for me. Thanks
