### ISSUE TITLE
Correct use of the module

### ISSUE THREAD

**Issue by Angelk90** [prscX/react-native-app-tour#25]
@prscX : 
Hi, I have the following graphics.
I wanted to know if it would be possible to make sure that the subjects in which the event should take place, the subjects in question that are circled are:
1) Those in the status bar, the component I use is:
`import {ThemeProvider, Toolbar} from 'react-native-material-ui'
`
```
<ThemeProvider>
          <Toolbar
            centerElement="Title"
            searchable={{
              autoFocus: true,
              placeholder: 'Search',
              onChangeText: text => {
                this.setState({ pageMovie: 1, pageTv: 1, pageActor: 1, indicatorMovie:true, indicatorTv:true, indicatorActor:true  },()=>{
                this.search(text, 1);
                });
              },
            }}
            rightElement={{
              actions: ['keyboard-voice','favorite','tv'],
              menu: {
                labels: ['Seleziona il numero di colonne'],
              },
            }}
            onRightElementPress={e => {
              console.log(e)
              if (e.index != undefined) {
                if (e.action == 'keyboard-voice' && e.index == 0) this._speech();
                if (e.action == 'favorite' && e.index == 1) this.props.navigation.navigate('Pref');
                if (e.action == 'tv' && e.index == 2) this.props.navigation.navigate('Xml');
                if (e.action == 'menu' && e.index == 0)
                  this.setState({ singleColumnPickerVisible: true });
              }
            }}
            style={{ container: { backgroundColor: '#4589f2' } }}
          />
        </ThemeProvider>
```
2) The elements of the tab, the component I use is:
`import {TabView, TabBar} from 'react-native-tab-view';
`

  ```
        <TabView
            navigationState={this.state}
            renderScene={this._renderScene}
            renderTabBar={this._renderHeader}
            onIndexChange={this._handleIndexChange}
          />
```

```
  _renderIcon = ({ route }) => (
    <Icon2 name={route.icon} size={24} style={styles.icon} />
  );

  _getLabelText = ({ route }) => route.title;

  _renderHeader = props => (
    <TabBar
      {...props}
      getLabelText={this._getLabelText}
      renderIcon={this._renderIcon}
      labelStyle={styles.label}
      tabStyle={styles.tab}
      style={styles.tabbar}
      indicatorStyle={styles.indicator}
    />
  );
```

3) Elements that do not exist, but only positions, for example:
- in the other on the right
- in the upper left
- bottom right
- bottom left
- in the center

![screenshot_20180615-164319](https://user-images.githubusercontent.com/20476002/41474805-449dab50-70bd-11e8-88c9-f727dc77173b.jpeg)
![screenshot_20180615-164458](https://user-images.githubusercontent.com/20476002/41474806-44d4c5d6-70bd-11e8-870c-0956de03b110.jpeg)

P.Š.
In the project https://github.com/prscX/react-native-taptargetview, I had a question with a code example, would it be possible to make the issues still accessible?

**Comment by Angelk90** [comment]
@prscX : 
I looked at the proposed example, to do a test with the button, but with I understand it does not seem to work the sequence that is the organized tour.

I'm trying directly to put the button in the main component without creating a support component, as you do with top, center, bottom.

It works only if you click on the button, then on the onPress event.

Code:


```
<Button
            key={'Top Left'}
            title={'Info'}
            ref={ref => {
              this.button1 = ref

              let props = {
                order: 12,
                title: 'This is a target button 1',
                description: 'We have the best targets, believe me',
                outerCircleColor: '#3f52ae',
                cancelable: false
              }

              this.props.addAppTourTarget &&
                this.props.addAppTourTarget(AppTourView.for(ref, { ...props }))
            }}
            onPress={() => {
              let props = {
                order: 11,
                title: 'Cerca i tuoi film',
                description: 'We have the best targets, believe me',
                outerCircleColor: '#4589f2'
              }

              let targetView = AppTourView.for(this.button1, {
                ...props
              })

              AppTour.ShowFor(targetView)
            }}
          />
```

I also tried how you do it using a support component, like you do with top, center, bottom.
But it gives me the following error:

 ![](https://i.imgur.com/PCEAefH.jpg)

**Comment by prscX** [comment]
Thanks Angelk90 for raising the issue and sharing the snippet.

You need to check for `ref` is not undefined/null validation,  if it is invalid please don't add it to tour.

Thanks
</ Pranav >

**Comment by Angelk90** [comment]
@prscX :  What do you mean? Could you give an example?

**Comment by prscX** [comment]
Hi @Angelk90: Before calling `AppTourView. for` API please add a validation statement similar to below one:

```
if (ref !== undefined && ref !== null) {
  AppTourView.for(ref)
}
```

Please let us know in case you still face the same issue.

Thanks
</ Pranav >

**Comment by Angelk90** [comment]
@prscX : Hi, I did as you say.

Code:

```       

<Button
          key={'Top Left'}
          title={'Top'}
          ref={ref => {
            let props = {
              order: 1,
              title: 'This is a target  1',
              description: 'We have the best targets, believe me',
              outerCircleColor: '#4589f2',
            }

            if (ref !== undefined && ref !== null){
              let targetView = AppTourView.for(ref, {
              ...props
            })
            this.appTourTargets.push(targetView);
            //AppTour.ShowFor(targetView)

            }

          }}
          onPress={() => {

          }}
        />


<Button
            key={'Top Left'}
            title={'Bottom'}
            ref={ref => {

              let props = {
                order: 2,
                title: 'This is a target  2',
                description: 'We have the best targets, believe me',
                outerCircleColor: '#4589f2'
              }

              if (ref !== undefined && ref !== null){
                let targetView = AppTourView.for(ref, {
                ...props
              })

              this.appTourTargets.push(targetView);
              //AppTour.ShowFor(targetView)

              }

            }}
            onPress={() => {

            }}
          />
```

The problems are as follows:

- The "Bottom" button is started first, which has order by 2 instead of "Top", which has order by 1.

- The sequence does not start.

Surely I'm going wrong, you can put an example in:
https://github.com/prscX/react-native-app-tour/blob/master/Example/App.js

Where you do not use other components created.

I've also added the <Top> component you created, and this is what it says:
The component Top starts, even if it has order by 12, and that's it, no sequence starts.

**Comment by Angelk90** [comment]
@prscX : Referring to the previous message.
Some bugs / problems I found on android.

1) Whenever the effect starts, the status bar disappears, it becomes black.
2) Sometimes it happens that you start multiple instances of the same, then to close the effect, you have to click several times outside it to close it.
3) If the effect is active, then there is a target activated with effect if you start the reload, it remains active even after reloading the app, debugging phase.

**Comment by Angelk90** [comment]
@prscX : Are there any news?

**Comment by Angelk90** [comment]
@prscX : Are there any news?

**Comment by Angelk90** [comment]
@prscX : Are there any news?

**Comment by Angelk90** [comment]
@prscX : Are there any news?

**Comment by Angelk90** [comment]
@prscX : By chance there are news about the open question?

**Comment by Angelk90** [comment]
@prscX : By chance there are news about the open question?

**Comment by KalebMatthews** [comment]
Hi @Angelk90 ,

One of the easiest solutions for the multiple instances of the tour running is to force the component to only run once. The brute force way to do this is to create a variable for "tour started" and in your component's ref code to add a check for that. Like this:

```
<Button
          key={'Top Left'}
          title={'Top'}
          ref={ref => {
            let props = {
              order: 1,
              title: 'This is a target  1',
              description: 'We have the best targets, believe me',
              outerCircleColor: '#4589f2',
            }

            /** NOTE: Reference the code change to the variable tourStarted **/
            if (ref !== undefined && ref !== null && !this.tourStarted){
               /** Immediately set the variable to prevent any additional instance from starting **/
               this.tourStarted = true;

              let targetView = AppTourView.for(ref, {
              ...props
            })
            this.appTourTargets.push(targetView);
            //AppTour.ShowFor(targetView)

            }

          }}
          onPress={() => {
                 this.tourStarted = false;
          }}
        />


<Button
            key={'Top Left'}
            title={'Bottom'}
            ref={ref => {

              let props = {
                order: 2,
                title: 'This is a target  2',
                description: 'We have the best targets, believe me',
                outerCircleColor: '#4589f2'
              }

              if (ref !== undefined && ref !== null){
                let targetView = AppTourView.for(ref, {
                ...props
              })

              this.appTourTargets.push(targetView);
              //AppTour.ShowFor(targetView)

              }

            }}
            onPress={() => {

            }}
          />
```
* Code is taken and modified from the example provided previously in this conversation.

Of course, this would cause problems for any additional tour elements in the sequence so multiple variables might be needed. I just started trying this package out today so I am still trying to find better ways to do things. I just thought I would answer since you have not gotten an answer for a long time. Brute force or not it is a short-term solution (not a great one admittedly).

**Comment by prscX** [comment]
Thanks @KalebMatthews for sharing your approach. I hope shared approach would have worked.

Thanks
</ Pranav >
