### ISSUE TITLE
file not found in iOS and No resourcefound in android

### ISSUE THREAD

**Issue by WCChimiiz** [prscX/react-native-app-tour#3]
when  I run iOS 
./node_modules/react-native-app-tour/ios/RNAppTour.h:3:9: fatal error: 'MaterialShowcase/MaterialShowcase-Swift.h' file not found

when  I run android
/android/app/build/intermediates/res/merged/debug/values-v24/values-v24.xml:4: AAPT: Error retrieving parent for item: No resourcefound that matches the given name 'android:TextAppearance.Material.Widget.Button.Colored'.

/android/app/build/intermediates/res/merged/debug/values-v24/values-v24.xml:3: error: Error retrieving parent for item: No resource found that matches the given name 'android:TextAppearance.Material.Widget.Button.Borderless.Colored'.

/android/app/build/intermediates/res/merged/debug/values-v24/values-v24.xml:4: error: Error retrieving parent for item: No resource found that matches the given name 'android:TextAppearance.Material.Widget.Button.Colored'.

**Comment by prscX** [comment]
Thanks @WCChimiiz for raising the issue.

**iOS:** Did you followed iOS installation steps? Basically need to init and install `Pods` in your app
**Android:** Can you please share `buildToolsVersion` of your app. Please note that this is supported only SDK 25 >

Thanks
Pranav

**Comment by congnguyen91** [comment]
@WCChimiiz 
IOS: 
![screen shot 2018-03-22 at 15 40 19](https://user-images.githubusercontent.com/18322684/37759850-6fb9f8ca-2de7-11e8-84f6-7dc32dc8ec74.png)
Add pod xproj to your project framework, re-embed lib material showcase again.
When u see your lib with clearly color like this -(opacity = 1)
![screen shot 2018-03-22 at 15 44 03](https://user-images.githubusercontent.com/18322684/37760016-07ac903e-2de8-11e8-87e6-608f5060b777.png)
=> correct
=====
Android: let use -sdk 25, 26 ...
    compileSdkVersion 26
    buildToolsVersion "26.0.1"

**Comment by congnguyen91** [comment]
@prscX  Let note it on read me or link to this issue :) thanks
@WCChimiiz  Please follow our example 👍 It should run :)

**Comment by prscX** [comment]
Thanks @congnguyen91 for the response.

I will add this issue in `README`, so that it will help folks who encounter the same issue.

Thanks
Pranav

**Comment by WCChimiiz** [comment]
@prscX @congnguyen91 
sorry all
now I'm fix and then got new fork

**Comment by prscX** [comment]
No problem @WCChimiiz, Please feel free to share PR/Suggestions in case you feel something can be improved.

Please let us know in case you face any issues, lets make community strong and help folks with our work 😄 

Thanks
Pranav

**Comment by congnguyen91** [comment]
@WCChimiiz I have seen your README.md - wonderful. Could you make a best clear README for this project :) like that about this iOS/Android issue. You are alway welcome 👍 to make a merge quest to master branch.

**Comment by LeandroGartner** [comment]
Hi!
I'm trying to install react-native-app-tour on my project but I'm getting this error. I try to resolve it by following this steps but it not work for me, any idea? Tanks you!

<img width="1507" alt="captura de pantalla 2018-04-03 a las 9 32 39" src="https://user-images.githubusercontent.com/33311693/38235653-2613665e-3722-11e8-8cbe-c3c72768af2a.png">
<img width="1518" alt="captura de pantalla 2018-04-03 a las 9 32 17" src="https://user-images.githubusercontent.com/33311693/38235662-2cb9847a-3722-11e8-9c79-5a9317509026.png">
<img width="267" alt="captura de pantalla 2018-04-03 a las 9 32 48" src="https://user-images.githubusercontent.com/33311693/38235671-3413753c-3722-11e8-8c24-340d57f48c30.png">
<img width="553" alt="captura de pantalla 2018-04-03 a las 9 33 03" src="https://user-images.githubusercontent.com/33311693/38235672-342e5c12-3722-11e8-9d62-8164b8359449.png">

**Comment by anniewey** [comment]
@congnguyen91 @prscX My build is still failing after `pod install` and add Pods.xcodeproj to project framework. I can't find the MaterialShowcase.framework anywhere

**Comment by shubhanus** [comment]
After doing all above steps i am getting material showcase not found please help.

**Comment by prscX** [comment]
Thanks @shubhanus for reporting the issue.

We have added setup video on how to add the native library. Can you please try by following same steps. Let us know in case it does not work.

Thanks
</ Pranav >

**Comment by shubhanus** [comment]
Thanks i will try and let u know if anything wont workout.

**Comment by shubhanus** [comment]
@prscX i have tried that video thing, that is from material-showcase-ios and there in no package aromajoin/material-showcase-ios in my node_module, so do i need to install one more package for that ??

**Comment by shubhanus** [comment]
@prscX I have used old method and just we need to do pod install in **./node_modules/react-native-app-tour/ios** then open **xcode** and follow @congnguyen91 instructions. if we get swift version is not define then in xcode click on **frameworks>Pods.xcodeproj** and search for **swift language version** and select **Swift 3.3**. and that will work!!!!

I think in docs you should remove that video that might be confusing just keep that pod install line.

**Comment by lutakyn** [comment]
I think the best solution is for the library owner to add a .podspec file to the project. React native is advising people to stop manual linking because they can break the code.Thank you.

**Comment by prscX** [comment]
@lutakyn: Thanks for bringing this up, we have already added .podspec file to iOS folder and is compatible with latest RN61. Please follow installation steps. Let me know if you face any problem.

**Comment by khagi** [comment]
sorry guys I don't know whats I did a mistake each and every step I followed android working fine but in ios same issue occurred 
![Screenshot 2020-04-17 at 11 35 38 AM](https://user-images.githubusercontent.com/3608935/79538402-ec411680-80a1-11ea-8b99-99564de7e30c.png)
![Screenshot 2020-04-17 at 11 36 25 AM](https://user-images.githubusercontent.com/3608935/79538423-f3682480-80a1-11ea-9d8c-d416ba0f1e84.png)
![Screenshot 2020-04-17 at 11 36 43 AM](https://user-images.githubusercontent.com/3608935/79538430-f4995180-80a1-11ea-81fe-c361de852377.png)
![Screenshot 2020-04-17 at 11 37 10 AM](https://user-images.githubusercontent.com/3608935/79538432-f531e800-80a1-11ea-8258-975b91ad6570.png)
![Screenshot 2020-04-17 at 11 37 18 AM](https://user-images.githubusercontent.com/3608935/79538436-f6631500-80a1-11ea-9324-962854520309.png)

**Comment by prscX** [comment]
Could you please share RN version. I would recommend to migrate to RN61, it is easy to do setup and has default pod support.

**Comment by khagi** [comment]
> Could you please share RN version. I would recommend to migrate to RN61, it is easy to do setup and has default pod support.

I,m Using This version "react-native": "0.60.4"

**Comment by khagi** [comment]
> Could you please share RN version. I would recommend to migrate to RN61, it is easy to do setup and has default pod support.

**Comment by prscX** [comment]
Is it possible to upgrade to RN61, it will be easy to do the setup.

**Comment by khagi** [comment]
> Is it possible to upgrade to RN61, it will be easy to do the setup.

Thanks, I will check all impact area and upgrade  RN61 then I will let you know. it's working or not.

**Comment by jalajbridgera** [comment]
Hello @prscX , i am also stuck in the ios build and getting the below error. I am using RN0.61. added the materialshowcase in framework also. Please can you help, i am stuck for long in this, as android it is working fine
![79538402-ec411680-80a1-11ea-8b99-99564de7e30c](https://user-images.githubusercontent.com/54837121/80367000-ee785180-88a7-11ea-8be6-e3fe8059a9ce.png)

**Comment by kgauravBridgera** [comment]
'MaterialShowcase/MaterialShowcase-Swift.h' file not found error in AppTour.h. On pod update I can see the below logs :
Installing MaterialShowcase (0.7.1)
Installing RNAppTour (1.0.3).
Please guide me over this. I have seen the docs and issues over a week, please help.

**Comment by prateekchitransh1907** [comment]
No pod file in or ios folder in node modules when installed. 

pod install in ./node_modules/react-native-app-tour/ios ---- no pods file to install

**Comment by StefanoCremona** [comment]
I'm stuck in the same situation of @prateekchitransh1907 and @kgauravBridgera .
I couldn't put `use_frameworks!` in my Podfile because of the existing configuration (it generates conflicts).
Any workaround?
