### ISSUE TITLE
Cant build release

### ISSUE THREAD

**Issue by stokesbga** [prscX/react-native-app-tour#32]
I have been looking into this for 3 days now and I feel defeated...
Works flawlessly on Debug, but as soon as I run on release - following all instructions - i get this during runtime. (builds fine)

 
<img width="1003" alt="screen shot 2018-06-25 at 3 42 33 am" src="https://user-images.githubusercontent.com/8782370/41836799-c61dec44-7829-11e8-8c58-40599bb56db7.png">

Any ideas?
Thanks

**Comment by prscX** [comment]
@stokesbga: I would really like to appreciate your effort and time in order to improve this library. Based on solution provided, I am also looking into how we can improve the installation steps.

Can you please share you code snippet of how you are invoking `ShowSequence` API.

Thanks
</ Pranav >

**Comment by stokesbga** [comment]
Sure!
<img width="585" alt="screen shot 2018-06-25 at 4 10 21 am" src="https://user-images.githubusercontent.com/8782370/41838215-cd253d72-782d-11e8-8293-ed70c2093959.png">
<img width="383" alt="screen shot 2018-06-25 at 4 10 30 am" src="https://user-images.githubusercontent.com/8782370/41838217-cfc92b56-782d-11e8-8c84-c59145ef4d42.png">
<img width="602" alt="screen shot 2018-06-25 at 4 11 08 am" src="https://user-images.githubusercontent.com/8782370/41838220-d182aada-782d-11e8-9be8-af1685489522.png">

**Comment by prscX** [comment]
Hi @stokesbga, I can understand your pain. It is difficult here to analyse the root cause of the issue.

Looks like it is trying to render tour target which does not exists when the call comes to native wrapper. Can you please replace native `ShowSequence` method impl with below snippet. I have added a check for targets count:

Class: `RNAppTour.m`
Method: `ShowSequence`

```

RCT_EXPORT_METHOD(ShowSequence:(NSArray *)views props:(NSDictionary *)props)
{
    targets = [[MutableOrderedDictionary alloc] init];
    for (NSNumber *view in views) {
        [targets setObject:[props objectForKey: [view stringValue]] forKey: [view stringValue]];
    }

    if ([[targets allKeys] count] <= 0) return;
    
    NSString *showTargetKey = [ [targets allKeys] objectAtIndex: 0];
    [self ShowFor:[NSNumber numberWithLongLong:[showTargetKey longLongValue]] props:[targets objectForKey:showTargetKey] ];
}
```
This is just to verify whether we are getting target or not.

Thanks
</ Pranav >

**Comment by prscX** [comment]
Hi @stokesbga, Any luck?

Thanks
</ Pranav >

**Comment by stokesbga** [comment]
sorry about the delay - just got a chance to try it out. No crash, but view stops loading

![screen shot 2018-06-26 at 9 51 22 am](https://user-images.githubusercontent.com/8782370/41917195-c6f04316-7927-11e8-8588-4536498bdc21.png)

![screen shot 2018-06-26 at 9 52 22 am](https://user-images.githubusercontent.com/8782370/41917187-c44bb884-7927-11e8-8abd-7bfd0c75605c.png)

**Comment by prscX** [comment]
Hi @stokesbga: Looks like the view `ref` you are passing is undefined || null. Can you please add a debugger and verify they reference you are passing to `AppTourView.for` is correct.

Please let me know your findings.

Thanks
</ Pranav >

**Comment by stokesbga** [comment]
I'm sure that is happening, but just bizarre considering the `if(!ref) return` and the fact that it works on development

**Comment by stokesbga** [comment]
I have isolated the problem to being related to the `<View/>` tag. As soon as I replace VIew with Button, as in the example, it works. W T F? I tried changing height, width, collapsable (i know its for android but just for the sake of coverage), flex, background color, adding text children. Im using a view with position: 'absolute' and transparent background to get the circle to focus on an element underneath.

**Comment by prscX** [comment]
Thanks @stokesbga for sharing the details.

Thats weird because the issues is happening only on release mode. Ideally iOS should not have any issues with View, today I will try the same impl using position as absolute and will share the finding.

Thanks 
</ Pranav >

**Comment by stokesbga** [comment]
Switching View to Button or TouchableOpacity works.. For now, that is the quick fix. Ill look into this further eventually, but I have already ripped out all my hair, so it probably wont be for some time.
