### ISSUE TITLE
resolve tag error persist

### ISSUE THREAD

**Issue by hamswaldenkv** [prscX/react-native-app-tour#35]
Hello i have that persisting error.
Tring to resolve view with tag (x) which doesnt exist

this is my code 
`<Button
          key={'Center Left'}
          title={'Center Left'}
          ref={ref => {
            if (!ref) return

            let props = {
              collapasable: false,
              order: 23,
              title: 'This is a target button 3',
              description: 'We have the best targets, believe me',
              outerCircleColor: '#3f52ae'
            }

            this.props.addAppTourTarget &&
              this.props.addAppTourTarget(AppTourView.for(ref, { ...props }))
          }}
          onPress={() => {}}
        />`

Can anyone help me to resolve this?

**Comment by prscX** [comment]
Thanks @hamsddxn for raising the issue.

Can you please share the platform you are trying to run the example. iOS/Android

Thanks 
</ Pranav >

**Comment by hamswaldenkv** [comment]
Application Target Platform:
Windows

Development Operating System:
Android api 23

Build Tools:
React Native version:
0.55.4

**Comment by prscX** [comment]
@hamsddxn: You can try it by using View component for Button it might now work.

Thanks
</ Pranav >
