### ISSUE TITLE
Call back on success

### ISSUE THREAD

**Issue by yoedfried** [prscX/react-native-app-tour#38]
Hi,
There is a way to add call back on success after ShowFor or after step in sequence?
Is there event that I can subscribe to after ShowFor?

Thanks,
Yoed

**Comment by prscX** [comment]
Thanks @yoedfried for raising the query.

Yes, we do have support for event listeners. You can add a listener for the `onFinishSequenceEvent` event:

Please refer [Example/App.js](https://github.com/prscX/react-native-app-tour/blob/master/Example/App.js) class for the reference.

Let me know incase it does not work.

Thanks
</ Pranav >

**Comment by yoedfried** [comment]
Thanks for the quick response.
This I know and used. I searching for the equivalent of this event for ShowFor.

**Comment by prscX** [comment]
@yoedfried: Got you :)

At present we don't have support for `ShowFor` event listener. Please give we some time I will have this in place.

Thanks
</ Pranav >

**Comment by prscX** [comment]
Closing the issue since the requested feature is not support. Please feel free to share PR.

Thanks
</ Pranav >
