### ISSUE TITLE
how to surround a search bar ?

### ISSUE THREAD

**Issue by sarinupreti** [prscX/react-native-app-tour#40]
how do i surround a  search bar as exactly as shown in the IOS tutorial

**Comment by prscX** [comment]
Thanks @sarinupreti for raising the query.

Can you please share the screenshot of what exactly you are looking for. 

> **Please Note:** Rect targets are currently not supported by the native libraries.

Thanks
</ Pranav >

**Comment by sarinupreti** [comment]
![image](https://user-images.githubusercontent.com/18618641/45283704-4eb55680-b4fe-11e8-8165-ce4da9efa586.png)


like this

**Comment by Noitidart** [comment]
@sarinupreti this would be a rect target (not yet supported).

**Comment by yac28** [comment]
Rect targets are currently not supported yet?

**Comment by prscX** [comment]
React Targets are not supported by native integrated libraries. Considering this closing the issue.

Thanks
</ Pranav >
