### ISSUE TITLE
Android effect on the <View /> tag

### ISSUE THREAD

**Issue by Angelk90** [prscX/react-native-app-tour#43]
Hi  @prscX, Would it be possible to apply the effect not only on the button tag but also on the View tag?

**Comment by Angelk90** [comment]
@prscX :  Hi, are there any news about it?

**Comment by prscX** [comment]
Thanks @Angelk90 for raising the query.

Can you please elaborate your query. My apologies, but I am not able to visualize your reference. 

Thanks
</ Pranav >

**Comment by Angelk90** [comment]
Hi @prscX, consider this image ![](https://i.imgur.com/k5bCT2L.jpg)

I would like the effect to be possible here as well.

**Comment by prscX** [comment]
@Angelk90: It is possible you can provide the reference to the API to show tour.

Thanks
</ Pranav >
