### ISSUE TITLE
Cannot read property 'ShowSequence' of undefined

### ISSUE THREAD

**Issue by sultanularefin** [prscX/react-native-app-tour#45]
Hi, I am coding in React-native for the last 5 months, I am trying to incorporate this package “react-native-app-tour ” to a project that I am "Tasked" with but unable to do so. 
Here is the Red Screen output of the Tasked project.
![screenshot_1537450240](https://user-images.githubusercontent.com/13745842/45821797-de7faf80-bd0b-11e8-92a1-b64385d26897.png)

I am able to run the Example project successfully and incorporated this package to another project (NativeBase-KitchenSink ) successfully. I am using these React-native and React  versions in all 3 projects ("react-native": "0.55.4", "react": "16.3.1" ) same as the Example project of this Repository.

Also I found in my Custom Component (Newsfeed.js) this function `componentWillMount() ` is not hitting/working .But this function is reached/worked and shows `console.log()` in other projects where this package is successfully implemented.

`componentWillMount() {

        console.log("I AM AT  componentWillMount");
        this.registerSequenceStepEvent()
        this.registerFinishSequenceEvent()
    }`

**Comment by samirakf** [comment]
I have this issue too, can anyone help?

**Comment by prscX** [comment]
Thanks @sultanularefin + @samirakf for raising the issue.

Basically this issue is encountered when the installation is mismatched. Can you please `unlink` library and follow all the installation steps defined in the `README`.

Thanks
</ Pranav >

**Comment by sultanularefin** [comment]
Hi, Pranav
Thank you for your suggestions. Based on your suggestions, I tried to **unlink** the package with this command `react-native unlink react-native-app-tour`

**Which gave me this output:**
![linking error](https://user-images.githubusercontent.com/13745842/46998777-60190080-d145-11e8-8c03-657d6754c387.jpg)

This is not caused by your package. i removed your package and ran `react-native link` which gave me the same error. And i don't know how to solve this.

**Regarding the readme file:** I followed everything of your package’s readme file [for android]. I successfully ran your package in 2 other projects. I inherited this project 6 months ago, it was using React-native version 0.46. I did update It recently to React-native version 0.55.4. I suspect there is something wrong in their implementation of React Navigation, but I am not certain.

Thanks

**Comment by sultanularefin** [comment]
Hi, Pranav you are right. I dig deeper on linking and found my react-native upgrade was not materialized properly. So, my first step was running this command `react-native upgrade`. Which causes some changes, I make some changes that are caused as a result of running this command `react-native upgrade`. Finally, I put everything of my **index.android.js** file to **index.js** file. Now it is working fine.

![nikunzo app tour integration](https://user-images.githubusercontent.com/13745842/47066589-6d4af380-d208-11e8-93f9-c64bae75e3b7.png)

Thanks Md. Sultanul Arefin.
