### ISSUE TITLE
Is there a way to get the shape of Object instead just a circle?

### ISSUE THREAD

**Issue by witalobenicio** [prscX/react-native-app-tour#46]
This library is great, and it would be nice if it worked the same as the native android.
In native android, this lib gets the shape of object, what I mean is...if we have a button that has a full width...we could see the entire button...not just a circle..

**Comment by witalobenicio** [comment]
I was wrong...in the native android...the circle is drawed below the view.

**Comment by prscX** [comment]
Thanks @witalobenicio for raising the issue. I am closing it since we have a solution for it.

Thanks
</ Pranav >
