### ISSUE TITLE
iOS not building - React/RCTUIManager.h file not found

### ISSUE THREAD

**Issue by ljuborados** [prscX/react-native-app-tour#48]
Followed the instructions, but iOS project is failing build, saying 'React/RCTUIManager.h' file not found  

![image](https://user-images.githubusercontent.com/18645781/46238362-9c99dd80-c38b-11e8-9147-3daa401a114e.png)
  
Any help would be greatly appreciated!

**Comment by prscX** [comment]
Thanks @ljuborados for raising the issue.

Can you please share your system and software stack in order to investigate the issue.

Thanks
</ Pranav >

**Comment by matinzd** [comment]
I get this error:   
`'MaterialShowcase/MaterialShowcase-Swift.h' file not found`

**Comment by prscX** [comment]
@matinzd: I would recommend to use latest version `V1.*` with RN61+ since it has support for cocoapods.

Thanks
</ Pranav >
