### ISSUE TITLE
How to show rectangle instead of circle ?

### ISSUE THREAD

**Issue by blntylmn** [prscX/react-native-app-tour#5]
Hi. Thanks for this plugin. It is awesome.
 How can we show rectangle around target instead of circle. Like below sample ?

![demo4](https://user-images.githubusercontent.com/15238168/37869111-ef3d14a6-2fc2-11e8-944d-98735d5d99ce.png)

**Comment by prscX** [comment]
Thanks @blntylmn for the query.

Yesterday @congnguyen91 and I were discussing that next we should focus on enabling targets for Rectangle as well and look today we have a request for the same 😄.

Hi @congnguyen91, 

Can you please share your thoughts on how we can enable this? Would you love to take this request? Please let us know your valuable feedback.

Thanks
Pranav

**Comment by congnguyen91** [comment]
In development :) @prscX  @blntylmn 
I want it both ios & android

**Comment by prscX** [comment]
Wow, That's Great @congnguyen91. 

Please let me know in case any help/support is needed.

Thanks
Pranav

**Comment by congnguyen91** [comment]
Done with New merge request https://github.com/prscX/react-native-app-tour/pull/10

**Comment by congnguyen91** [comment]
some animation with rectangle comming soon when I have free time :)

**Comment by prscX** [comment]
Many Thanks @congnguyen91 for the PR. I will review and merge the same.

Thanks
</ Pranav >

**Comment by lrenzetti** [comment]
@prscX any news about this ?

**Comment by LuisBonsembiante** [comment]
Hello everyone.....any news about that?

**Comment by prscX** [comment]
Hi All: Closing this issue since it is not supported by native libraries we have integrated.

Thanks
</ Pranav >
