### ISSUE TITLE
Have a new release including fix for Android build

### ISSUE THREAD

**Issue by ygriguer-bhs** [prscX/react-native-app-tour#54]
Hi,

I've noticed you merged a week ago on master the fix about the build failure with gradle dependencies. Would it be possible to have a new release v0.0.17 including this fix? It would allow all your users not to fork or point to master branch.

Thank you in advance!

**Comment by prscX** [comment]
Sure @ygriguer-bhs. I am planning to push release tomorrow. Will keep you posted.

Thanks
</ Pranav >

**Comment by prscX** [comment]
Hi @ygriguer-bhs: I have push the release. Can you please install latest version and verify the same. Please let me know in case you face any issues.

Thanks
</ Pranav >
