### ISSUE TITLE
TourTarget onCancel

### ISSUE THREAD

**Issue by KalebMatthews** [prscX/react-native-app-tour#55]
Is there a way to add the ability to determine if a tour step was canceled (click outside the inner circle) using the onFinishSequenceEvent listener?

Use case: We have a navigation change from footer tabs to a menu button in the top corner. So naturally, we have the tour target centered around the new menu button. If the user clicks on the menu button in the tour I want to open the menu. However, if they cancel I don't want to do anything but remove the tour target. So either a canceled flag in the onFinishSequenceEvent or an onInnerCirclePress prop would work. Currently, the onFinishSequenceEvent only has a finish flag in the Event object which is always true.

Thanks for your assistance.

**Comment by booleanBoy** [comment]
I was just about to ask something similar, although less eloquently... Some way to determine whether or not the user tapped outside the coloured circle so I can cancel the tour would be really useful.

**Comment by prscX** [comment]
I am afraid to share but the requested feature is not supported by native libraries we have integrated. Closing issue in the absence of feature.

Thanks
</ Pranav >
