### ISSUE TITLE
undefined is not an object(evaluating RNApp.Tour.ShowSequence)

### ISSUE THREAD

**Issue by hunglythien1404** [prscX/react-native-app-tour#56]
Hi, im trying to use react-native-app-tour, i clone an example source code from https://github.com/prscX/react-native-app-tour, and i got this error, anyone can help ?. Thank you so much, and sorry for my bad English

![image](https://user-images.githubusercontent.com/44635375/48895067-cd236280-ee76-11e8-9c5f-52b597bced67.png)

**Comment by msnajib** [comment]
+1

**Comment by prscX** [comment]
Thanks @hunglythien1404 for raising the issue. This issue occurs when the installation steps got mismatch. Could you please verify all the steps through README.

Thanks
</ Pranav >

**Comment by prscX** [comment]
I would recommend to use latest released version `1.*` with RN61+ since it has default support for cocoapods.

Closing issue in favour of latest release and cocoapod support.

Thanks
</ Pranav >

**Comment by PrantikMondal** [comment]
Still i am getting same issue in the latest version 1.0.3

**Comment by sunviwo** [comment]
Hi, I'm getting the same issue. Any fix so far ?

**Comment by alemkhodadadi** [comment]
still having same problem. any fix?
