### ISSUE TITLE
No visible @interface for 'MaterialShowcase' declares the selector 'setIsTapRecognizerForTargetView:'

### ISSUE THREAD

**Issue by msnajib** [prscX/react-native-app-tour#58]
if I command can run well, but I can't apply `cancelable` props. Please, Help.

![screen shot 2018-12-20 at 12 31 40 am](https://user-images.githubusercontent.com/31720790/50237208-e32d3000-03ee-11e9-87ea-0b0a918adb5d.png)

**Comment by msnajib** [comment]
@prscX ..

**Comment by msnajib** [comment]
@prscX solved!

I replace `setIsTapRecognizerForTargetView` to `setIsTapRecognizerForTagretView`.

**Comment by prscX** [comment]
@MuhammadSNajib: Could you please share PR for the same in order to help community.

Thanks
</ Pranav >
