### ISSUE TITLE
Use table view from material-showcase-ios example

### ISSUE THREAD

**Issue by ejkkan** [prscX/react-native-app-tour#60]
is it possible to mark a row as in the gif example in the readme?
If so, could you please post an example. I have tried to figure this out myself but not come to any conclusion

**Comment by prscX** [comment]
Thanks @ejkkan for raising the query.

As part of current implementation, we don't have support for Rect components.

Thanks
</ Pranav >

**Comment by prscX** [comment]
Rect component is not supported by native libraries we have integrated. Closing the issue in the absence of feature.

Thanks
</ Pranav >
