### ISSUE TITLE
Regarding Pod Install

### ISSUE THREAD

**Issue by Meninblack007** [prscX/react-native-app-tour#61]
Why are we doing pod install inside node_modules/react-native-app-tour ?

**Comment by prscX** [comment]
Thanks @Meninblack007 for raising the query.

It is needed because the library is a RN native module bridge around iOS library and in order to install these we need to install it through cocoapods.

Thanks
</ Pranav >

**Comment by Meninblack007** [comment]
@prscX I don't know how react-native link works. I always prefer manual linking via cocoapods and if I try linking your library, it fails. So I made few fixes, which will fix manual linking via cocoapods and you don't have to install pods inside node_modules/react-native-app-tour.

https://github.com/Meninblack007/react-native-app-tour/commits/master

**Comment by idoamram2gether** [comment]
Hi!
I couldn't integrate this library successfully to iOS.
i'm getting `dyld: Library not loaded: @rpath/libswiftCore.dylib`.
Do you know why i get it and/or how can i fix it?
Thanks a lot!
Ido

**Comment by prscX** [comment]
I would recommend to use latest released version `1.*` with RN61+ since it has default support for cocoapods.

Closing this issue as it is fixed in RN61+ with support for pods.

Thanks
</ Pranav >
