### ISSUE TITLE
dyld: Library not loaded: @rpath/libswiftCore.dylib

### ISSUE THREAD

**Issue by idoamram2gether** [prscX/react-native-app-tour#62]
Hi @prscX ! :)
I followed the iOS setup instructions and this is what i get:

```
dyld: Library not loaded: @rpath/libswiftCore.dylib
  Referenced from: /private/var/containers/Bundle/Application/0481DC50-05CC-4D8A-8779-8477FFFA6A2A/imagine.app/Frameworks/MaterialShowcase.framework/MaterialShowcase
  Reason: image not found
Message from debugger: Terminated due to signal 6
```

Tried to run on iPhone 5 device and on simulator.

Do you know how can i solve it? couldn't find any working solution on similar issues on stackoverflow.

Thanks in advance,
Ido

**Comment by adityasonel** [comment]
I discovered that there is an "Always Embed Swift Standard Libraries" flag in the Build Settings that needs to be set to YES. It was NO by default!

Build Settings > Always Embed Swift Standard Libraries

After setting this, clean the project before building again.

![Q6cAf](https://user-images.githubusercontent.com/28022451/56715550-a2a34180-6755-11e9-8f6f-7dadebab584f.png)

And now it's working :D

**Comment by prscX** [comment]
Thanks @adityasonel for sharing the approach.

Closing this issue.

</ Pranav >
