### ISSUE TITLE
Cannot get iOS to build in "release"

### ISSUE THREAD

**Issue by davidbutz** [prscX/react-native-app-tour#63]
Davids-MacBook-Pro:ios davebutz$ pod --version
1.5.0

package.json:
"react-native-app-tour": "0.0.18",

Works in schema debug, not in release.
double, triple checked the set up and i'm lost.

the error i get is in RNAppTour Target,

"Lexical or Preprocessor issue"
Could not build module 'UIKit'
chrono file not found time.h

and then Parse issues. 

Any help would be appreciated.

**Comment by radik** [comment]
@davidbutz Did you find a solution?

**Comment by davidbutz** [comment]
Yes and No. I like this library, but it's been hell to keep stable. Every new pod install will cause the same issue.

So here's what I do to "work-around" this: 
1) Keep a fresh project with ONLY this module installed.
2) remove entirely the npm + projects in Xcode
3) reinstall. BUT... don't react-native link.......
4) (laughing in head) *find* whereever-the-heck the materialframework is located. put it in the /project/ios folder. - drag it from there..

5) Most important part... make sure the libRNAppTour.a is AFTER your project lib[PROJECT].a build.... 

Then it's a game. I build the other Xcode project first... in either schema (which one i want)
Then i go back to my project. clean build folder. Close Xcode. Open ... wait for pre-build to finish. 
Then build the project W/O the libRNAppTour.a 
Then build it W it in...
Seems to work. Good luck.

I am a small prototyping shop, so I'm sure the experts might have LOTS to say about this :) !

**Comment by prscX** [comment]
I would recommend to use latest released version `V1.*` with RN61+ since it has default support for cocoapods.

Closing this issue since RN61+ has support for pods.

Thanks
</ Pranav >
