### ISSUE TITLE
after called once,recall apptour when state change on same page 

### ISSUE THREAD

**Issue by yash-vaghela21** [prscX/react-native-app-tour#72]
i want to recall appTour to load again when my state change when onPress called on same page??
is it possible? or is it called once only?

**Comment by prscX** [comment]
Thanks @ydv0121 for raising query. Yes, it is possible. You can invoke tour from `componentDidUpdate` API.

Thanks
</ Pranav >

**Comment by yash-vaghela21** [comment]
> Thanks @ydv0121 for raising query. Yes, it is possible. You can invoke tour from `componentDidUpdate` API.
> 
> Thanks
> </ Pranav >

Thank you for suggestion..i will definitely try
