### ISSUE TITLE
Library not loaded MaterialShowcase

### ISSUE THREAD

**Issue by yash-vaghela21** [prscX/react-native-app-tour#74]
how to solve library no loaded?
 **dyld: Library not loaded: @rpath/MaterialShowcase.framework/MaterialShowcase**

![Screenshot 2019-07-03 at 9 39 30 AM](https://user-images.githubusercontent.com/37238045/60562768-913e6d00-9d76-11e9-9f02-f59ebb14f40b.png)

**Comment by selarom-epilef** [comment]
See https://github.com/prscX/react-native-app-tour/issues/62 and https://stackoverflow.com/questions/24993752/os-x-framework-library-not-loaded-image-not-found

**Comment by prscX** [comment]
I would recommend to use latest release version `1.*` with RN61+ since it has default support for cocoapods.

Thanks
</ Pranav >

**Comment by annaostapenko22** [comment]
@ydv0121 Did you solve this problem? Please let me know, because I have the same issue now and use RN 59

**Comment by yash-vaghela21** [comment]
> @ydv0121 Did you solve this problem? Please let me know, because I have the same issue now and use RN 59
> 
Yes.
Just pod install in `node_modules/react-native-app-tour/ios`
and add `Pods.xcodeproject` in `RNAppTour` Group which you need to create under your project
And add `MaterialShowcase.framework` in `Embedded Binaries`
