### ISSUE TITLE
Pod install failed with React 0.60.4

### ISSUE THREAD

**Issue by itsdante** [prscX/react-native-app-tour#75]
```
[!] Invalid `Podfile` file: 
[!] Invalid `RNAppTour.podspec` file: No such file or directory @ rb_sysopen - /Users/machintos/Documents/GitHub/project/node_modules/react-native-app-tour/ios/package.json.
```

Hey everyone, I just upgraded to 0.60.4 from 0.57, the library works well in the version but we had to upgrade to use some libraries. Now my problem lies with the "pod install" command after npm install. The project is new (some of the libraries weren't updating, so we decided to create a new project) and there were no problems with running the command with other libraries. But once I install react-native-app-tour, the pod install crashed with the error above

**Comment by arielayaviri** [comment]
Same problem here. Appreciate any help.

**Comment by TheNasCrazy** [comment]
Up ???

**Comment by itsdante** [comment]
@arielayaviri @TheNasCrazy I manage to actually fixed it, the RNAppTTour.podspec, is located within the ios folder, but it reference the package.json in the ios directory, while the package.json file is located one level outside of the folder. Please change to 

`../package.json`

from 

`package.json`

in the RNAppTour.podspec file

**Comment by TheNasCrazy** [comment]
@itsdante   But when I change and I try pod install il my project I Got : [!] No podspec found for `RNAppTour` in `../node_modules/react-native-app-tour`

**Comment by arielayaviri** [comment]
@itsdante thanks I'll try and let you know. I remember I did that before and had some problems with the pod install command similar to what @TheNasCrazy had. I'll try again. Thanks
