### ISSUE TITLE
Add button inside the tour

### ISSUE THREAD

**Issue by danieljgp2** [prscX/react-native-app-tour#76]
Is there a way to add a custom button inside of the tour circles ?  Like at the end of the android example gift

**Comment by itsdante** [comment]
you can just focus to the button your suggesting, I created a separate screen just for the purpose of showing the tour. hope this helps

**Comment by danieljgp2** [comment]
@itsdante Any idea about how to solve this issue https://github.com/prscX/react-native-app-tour/issues/78

**Comment by prscX** [comment]
Thanks @danieljgp2 for raising the query.

This library is wrapper around native libraries providing AppTour. I am afraid to share that native library does not have capability of adding custom UI.

Thanks
</ Pranav >
