### ISSUE TITLE
Command PhaseScriptExecution failed with a nonzero exit code

### ISSUE THREAD

**Issue by ravifullestop** [prscX/react-native-app-tour#79]
I have followed each step of readme file and still it is not running. The error is coming as below : 

Merging extracted architectures: x86_64
Replacing original executable with thinned version
Executable is /Users/team/Library/Developer/Xcode/DerivedData/abcd-evkuoknqqxlrrueyipqdrrbkpxqt/Build/Products/Debug-iphonesimulator/abcd.app/Frameworks/MaterialShowcase.framework/MaterialShowcase
Extracting x86_64 from MaterialShowcase
fatal error: lipo: input file (/Users/team/Library/Developer/Xcode/DerivedData/abcd-evkuoknqqxlrrueyipqdrrbkpxqt/Build/Products/Debug-iphonesimulator/abcd.app/Frameworks/MaterialShowcase.framework/MaterialShowcase) must be a fat file when the -extract option is specified
Merging extracted architectures: x86_64
fatal error: lipo: can't open input file: /Users/team/Library/Developer/Xcode/DerivedData/abcd-evkuoknqqxlrrueyipqdrrbkpxqt/Build/Products/Debug-iphonesimulator/abcd.app/Frameworks/MaterialShowcase.framework/MaterialShowcase-x86_64 (No such file or directory)
rm: /Users/team/Library/Developer/Xcode/DerivedData/abcd-evkuoknqqxlrrueyipqdrrbkpxqt/Build/Products/Debug-iphonesimulator/abcd.app/Frameworks/MaterialShowcase.framework/MaterialShowcase-x86_64: No such file or directory
Replacing original executable with thinned version
mv: rename /Users/team/Library/Developer/Xcode/DerivedData/abcd-evkuoknqqxlrrueyipqdrrbkpxqt/Build/Products/Debug-iphonesimulator/abcd.app/Frameworks/MaterialShowcase.framework/MaterialShowcase-merged to /Users/team/Library/Developer/Xcode/DerivedData/abcd-evkuoknqqxlrrueyipqdrrbkpxqt/Build/Products/Debug-iphonesimulator/abcd.app/Frameworks/MaterialShowcase.framework/MaterialShowcase: No such file or directory
Command PhaseScriptExecution failed with a nonzero exit code

**Comment by ravifullestop** [comment]
@prscX Can you please respond on it.

**Comment by ravifullestop** [comment]
@prscX Please respond

**Comment by prscX** [comment]
Thanks @ravifullestop for raising issue.

I would recommend to use latest released version `V1.*` with RN61+ since it has default support for cocoapods.

Thanks
</ Pranav >
