### ISSUE TITLE
Some questions

### ISSUE THREAD

**Issue by Angelk90** [prscX/react-native-app-tour#8]
@prscX : 
Since the project has been moved, I open a new question here.
The elements that I open as a matter are the same ones I had opened in this:
https://github.com/prscX/react-native-taptargetview/issues/4

If there are any news, let me know.

**Comment by anniewey** [comment]
@prscX A question here:
Is there any callback for `AppTour.ShowFor(appTourTarget)` to determine whether the dialog is close?

Because I'm trying to achieve _step by step guide_ which involved _user interaction_, rather than show sequence automatically.

**Example:** `Target 1 shown` -> `user tap on Target 1 and it closes, then Target 2 is shown right after Target 1 close.`

**Comment by anniewey** [comment]
@prscX A question here:
How do I determine `AppTour.ShowSequence(appTourSequence)` is done running? Is there any callback from this function? I need to know when user has finish the tour.

**Comment by prscX** [comment]
Thanks @anniewey for the query. Yes, We have sequence event listeners:

- `onShowSequenceStepEvent `

```
this.sequenceStepListener = DeviceEventEmitter.addListener(
      'onShowSequenceStepEvent',
      (e: Event) => {
        console.log(e);
      }
 );
```

- `onFinishSequenceEvent `

```
    this.finishSequenceListener = DeviceEventEmitter.addListener(
      'onFinishSequenceEvent',
      (e: Event) => {
        console.log(e);
      }
    );

```

Hope it will fullfill your requirements.

@congnguyen91 

Thanks
</ Pranav >

**Comment by anniewey** [comment]
@prscX Thank you! That's exactly what I look for. 👍

**Comment by Angelk90** [comment]
@prscX : There are news about the original post to which I referred?

**Comment by Angelk90** [comment]
@prscX : There are news about the original post to which I referred?

**Comment by mj-haghighiGH** [comment]
@prscX  
Hello!
Is it possible to change the font family of title and descriptions?
