### ISSUE TITLE
Fix podspec for RN 0.60.5+

### ISSUE THREAD

**Issue by Jayrene1** [prscX/react-native-app-tour#80]
```[!] Invalid 'Podfile' file:```
```[!] Invalid 'RNAppTour.podspec' file: No such file or directory @ rb_sysopen - /Users/joshuaarcega/Github/12Stone-Mobile/node_modules/react-native-app-tour/ios/package.json.```

Related issue: https://github.com/prscX/react-native-app-tour/issues/75

the package file path to `'package.json'`  should be changed to `'../package.json'` for automated builds. Our server builds its own node_modules, so this path issue will persist on release.

**Comment by emmab30** [comment]
Worked for me (until it's fixed on release version):

Move .podspec file from iOS folder to root node_modules/react-native-app-tour folder.

**Comment by prscX** [comment]
Thanks @Jayrene1 for raising issue.

I have added support for RN61+ in >= V1 of library. Could you please upgrade library to latest version and verify the same. Please follow README for the installation steps.

Thanks,
</ Pranav >
