### ISSUE TITLE
Error Build iOS

### ISSUE THREAD

**Issue by tamacroft** [prscX/react-native-app-tour#84]
it show error 
MaterialShowcase/MaterialShowcase-Swift.h' file not found
in RNApptour.h

btw i'm using react-native: 0.61.4

**Comment by prscX** [comment]
Thanks @tamacroft for raising issue.

Could you please share the library version as well. Requesting to use latest released version and follow installation steps for the same.

Thanks
</ Pranav >

**Comment by billdami** [comment]
I am seeing this same issue on react-native 0.61.3, using the latest version of this package (1.0.2)

**Comment by prscX** [comment]
@billdami: Did you added the native library to your Podfile?

Thanks
</ Pranav >

**Comment by Doha26** [comment]
Hi @tamacroft  ,
try to add this in your podfile

pod 'RNAppTour', :path => '../node_modules/react-native-app-tour/ios'

use_frameworks!

pod 'MaterialShowcase',:git => 'https://github.com/prscX/material-showcase-ios', :branch => 'swift-version-fix'

after that , run pod install.

also ensure that MaterialShowcase.framework is added in "link binaries with library" in your target Build phase and also in "Framework, library and embedded content".

and see if everything work properly

**Comment by prscX** [comment]
Thanks @Doha26 for sharing the installation steps.

@tamacroft: For details, please refer installation steps defined in `README`

Thanks
</ Pranav >
