### ISSUE TITLE
Can't run on RN 61.5 - IOS

### ISSUE THREAD

**Issue by movie4** [prscX/react-native-app-tour#89]
Hello!

```
/node_modules/react-native-app-tour/ios/RNAppTour.h:3:9: fatal error: 'MaterialShowcase/MaterialShowcase-Swift.h' file not found
#import "MaterialShowcase/MaterialShowcase-Swift.h"
```

Example not working

**Comment by Doha26** [comment]
Hi @movie4 ,
try to add this in your podfile

  pod 'RNAppTour', :path => '../node_modules/react-native-app-tour/ios'
  
  use_frameworks!

  pod 'MaterialShowcase',:git => 'https://github.com/prscX/material-showcase-ios', :branch => 'swift-version-fix'

after that , run pod install.

also ensure that MaterialShowcase.framework is added in "link binaries with library" in your target Build phase and also in "Framework, library and embedded content".

and see if everything work properly

**Comment by prscX** [comment]
Thanks @Doha26 for sharing the installation steps.

@movie4: Hope this would have helped you.

Thanks
</ Pranav >
